# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23def9a89edaad062410d74a766ae68e9dfd73e5762a4952cf39ad652fe089673da6f2f6fdd6269241414e37d2a34f8b5fd7863ac2b23381b1cd3e9c0eecfe5e

test:
  secret_key_base: 00f68b651760da270fa542dc8be4e571e260dca771e68c61ddfc25f8dbb2f135e4616e78a424bd0358bdc1e960931178299f95e0cc230a998f4ff2b2987a26ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
